package com.brianreber.gitstats;

import java.io.File;
import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.json.JSONException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 * The generic outline of a visualization page
 * 
 * @author breber
 */
public abstract class HtmlPage {

	/**
	 * The title of the project
	 */
	protected final String projectTitle;

	/**
	 * The title of the page
	 */
	protected final String pageTitle;

	/**
	 * The file to write the page to
	 */
	protected final String fileName;

	/**
	 * Creates a new HTMLPage with the given project title, file name, and page title
	 * 
	 * @param projectTitle the title of the project
	 * @param fileName the file to write to
	 * @param pageTitle the title of the page
	 */
	public HtmlPage(String projectTitle, String fileName, String pageTitle) {
		this.fileName = fileName;
		this.projectTitle = projectTitle;
		this.pageTitle = pageTitle;
	}

	/**
	 * Generates the content of the page, containing the visualization
	 * 
	 * @param commits the list of commits to use to generate the visualization
	 * @return the string to put in for the body of the main JS block
	 * @throws JSONException
	 */
	protected abstract String generateBody(List<Commit> commits) throws JSONException;

	/**
	 * Generates the HTML of the page and writes it to the file
	 * 
	 * @param commits the list of commits to use
	 */
	public void generatePage(List<Commit> commits) {
		try {
			DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
			DocumentBuilder docBuilder = docFactory.newDocumentBuilder();

			Document doc = docBuilder.newDocument();
			Element rootElement = doc.createElement("html");
			doc.appendChild(rootElement);

			Element head = doc.createElement("head");

			// Generate include for JSAPI
			Element script = doc.createElement("script");
			script.setAttribute("type", "text/javascript");
			script.setAttribute("src", "https://www.google.com/jsapi");
			head.appendChild(script);

			// Generate the JS for generating the graphs
			Element script2 = doc.createElement("script");
			script2.setAttribute("type", "text/javascript");
			script2.setTextContent(generateBody(commits));
			head.appendChild(script2);

			// Create the title
			Element title = doc.createElement("title");
			title.setTextContent(projectTitle + ": " + pageTitle);
			head.appendChild(title);

			// Add the head to the page
			rootElement.appendChild(head);

			// Generate the body
			Element body = doc.createElement("body");

			// Generate the top section of the page
			Element bodyHeading = doc.createElement("h2");
			bodyHeading.setTextContent(projectTitle + ": " + pageTitle);
			body.appendChild(bodyHeading);

			// Generate the Chart Div
			Element chartDiv = doc.createElement("div");
			chartDiv.setAttribute("id", "chart_div");
			chartDiv.setAttribute("style", "width: 100%; height: 700px;");
			body.appendChild(chartDiv);

			// TODO: generated by, copyright

			// Add the body to the html page
			rootElement.appendChild(body);

			// Generate HTML text
			TransformerFactory tf = TransformerFactory.newInstance();
			Transformer transformer;
			transformer = tf.newTransformer();

			DOMSource source = new DOMSource(doc);
			StreamResult result = new StreamResult(new File(fileName));
			transformer.transform(source, result);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}